### ISSUE TITLE
Functions are not called on localhost

### ISSUE THREAD

**Issue by yurivyatkin** [netlify/create-react-app-lambda#33]
I tried to run this locally. Here are the related steps (`[...]` means "omitted"):

```
$ ntl help
[...]
VERSION
  netlify-cli/2.12.0 linux-x64 node-v10.16.3
[...]
$ yarn -v
1.17.3

$ gcl git@github.com:netlify/create-react-app-lambda.git
$ cd create-react-app-lambda

$ yarn
[...]

$ ntl dev
```
I can confirm that calls to

```
http://localhost:8888/.netlify/functions/hello and
http://localhost:8888/.netlify/functions/async-dadjoke
```

work as expected, but clicking the buttons on the client (`http://localhost:3000`) causes them stuck in "Loading..." state, whereas in the console there is an error message:

```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```

(the response to the API call from the click handler being the content of `index.html`).

At the same time, the instance deployed to Netlify works fine (clicking the buttons yields the expected text underneath).

I tried to fiddle around with proxies as in https://www.youtube.com/watch?v=3ldSM98nCHI and the documentation, but did not get the local functions called from the client yet.

**Comment by ntrabue** [comment]
Hey I know this is old. I was playing around and ran into this issue as well. Try accessing the app on localhost:8888 instead of localhost:3000.

**Comment by sw-yx** [comment]
correct, since we moved to netlify dev we no longer need to fiddle around with proxies.

i tried to document this as best as i can, happy to take PRs for better docs

**Comment by carolina-cascade** [comment]
@ntrabue You saved after hours lost. I've been trying to access the lambda function in my localhost all day, getting 404 in my console no matter what I tried. I got access to the Playground, but did not realize my app was also served in localhost:8888. Thank you very, very much!

**Comment by susanstearns** [comment]
I'm having difficulty as well.

When I run the ntl dev command in my local environment:

![CRA-Lambda-screenshot](https://user-images.githubusercontent.com/9204382/71847313-2dcd2900-3092-11ea-9a5e-a3937dd06920.png)

- I'm able to access the react app via localhost:3000.
- http://localhost:3000/.netlify/functions/hello also displays the react app.
- localhost:8888 does not work.
- The port number for accessing lambda functions in the browser directly changes every time I start the servers by running ntl dev.  Using the given port number in the output from ntl dev (i.e., "Lamda server is listening on [portnumber]" message), http://localhost:[giveportnumber]/.netlify/functions/hello displays the json output as expected. 
- Clicking either button in the react app causes the console error "Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0" of index.  Status on hello fetch returns 200.

I tried running yarn upgrade but this had no effect.

Version Info: 
netlify-cli/2.25.0 darwin-x64 node-v12.13.0
yarn -v = 1.19.2

I'm a relative newbie at everything npm, incorporating libraries, react, etc so any help would be appreciated.  I started watching the video but wasn't sure if I should continue or what to do since you've made changes and no longer need to fiddle with proxies.

**Comment by sw-yx** [comment]
@susanstearns  can you show me your repo? or are you purely working off of this one?

**Comment by udayax** [comment]
> I'm having difficulty as well.
> 
> When I run the ntl dev command in my local environment:
> 
> ![CRA-Lambda-screenshot](https://user-images.githubusercontent.com/9204382/71847313-2dcd2900-3092-11ea-9a5e-a3937dd06920.png)
> 
> * I'm able to access the react app via localhost:3000.
> * http://localhost:3000/.netlify/functions/hello also displays the react app.
> * localhost:8888 does not work.
> * The port number for accessing lambda functions in the browser directly changes every time I start the servers by running ntl dev.  Using the given port number in the output from ntl dev (i.e., "Lamda server is listening on [portnumber]" message), [http://localhost:[giveportnumber]/.netlify/functions/hello](http://localhost:%5Bgiveportnumber%5D/.netlify/functions/hello) displays the json output as expected.
> * Clicking either button in the react app causes the console error "Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0" of index.  Status on hello fetch returns 200.
> 
> I tried running yarn upgrade but this had no effect.
> 
> Version Info: netlify-cli/2.25.0 darwin-x64 node-v12.13.0 yarn -v = 1.19.2
> 
> I'm a relative newbie at everything npm, incorporating libraries, react, etc so any help would be appreciated. I started watching the video but wasn't sure if I should continue or what to do since you've made changes and no longer need to fiddle with proxies.

facing same issue still. Is there any solution?

**Comment by swyxio** [comment]
i no longer work at netlify so feel free to @ the other employees

**Comment by udayax** [comment]
Thanks for your response @sw-yx 🙂
Somehow managed to fix that issue.
